# Author: ShelpAm
#
# This file is Generated by AI
#

from flask import Flask
import subprocess
import sys

dest = sys.argv[1]

app = Flask(__name__)


@app.route("/webhook", methods=["POST"])
def webhook():
    # You can add a GitHub secret validation here if needed
    print("Pulling from the server")
    subprocess.Popen(["git", "pull"])
    subprocess.Popen(["jekyll", "build"])
    subprocess.Popen(["mv", "_site", dest])
    return "OK", 200


if __name__ == "__main__":
    app.run(host="0.0.0.0", port=9001)
