# Author: ShelpAm
#
# This file is Generated by AI
#

from flask import Flask
import subprocess
import sys

if len(sys.argv) < 2:
    print("usage: python webhook_server.py <build-destination>")
    exit(1)

dest = sys.argv[1]

app = Flask(__name__)


@app.route("/webhook", methods=["POST"])
def webhook():
    # You can add a GitHub secret validation here if needed
    print(f"Webhook triggered. (Re)deploying files to {dest}")
    subprocess.Popen(["bash", "./tools/deploy.sh", dest])
    return "OK", 200


if __name__ == "__main__":
    app.run(host="0.0.0.0", port=9001)
